// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnrjurklebeecuissdng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZucmp1cmtsZWJlZWN1aXNzZG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjA1MTQsImV4cCI6MjA1NTc5NjUxNH0.Icbr6edahm8iHpCanVFeHJoGtWhSyV4g4mmoRs_y19A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);